### ISSUE TITLE
Input file

### ISSUE THREAD

**Issue by utpalmtbi** [donia-lab/MetaBGC#10]
Hi,

I can run metabgc search on example input files with a given protein family. But when I try with a metagenome file (fastq) I get the following error:

```
Traceback (most recent call last):
  File "/research/m197897/anaconda/envs/metabgc/bin/metabgc", line 8, in <module>
    sys.exit(main())
  File "/research/m197897/anaconda/envs/metabgc/lib/python3.7/site-packages/metabgc/metabgc_cmds.py", line 224, in main
    cli()
  File "/research/m197897/anaconda/envs/metabgc/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/research/m197897/anaconda/envs/metabgc/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/research/m197897/anaconda/envs/metabgc/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/research/m197897/anaconda/envs/metabgc/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/research/m197897/anaconda/envs/metabgc/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/research/m197897/anaconda/envs/metabgc/lib/python3.7/site-packages/metabgc/metabgc_cmds.py", line 213, in search
    prot_family_name, hmm_search_directory, output_directory, cpu)
  File "/research/m197897/anaconda/envs/metabgc/lib/python3.7/site-packages/metabgc/src/metabgcidentify.py", line 107, in mbgcidentify
    runidentify(allHMMResult, cutoff_file, filteredHMMResult, identifyReadIds)
  File "/research/m197897/anaconda/envs/metabgc/lib/python3.7/site-packages/metabgc/src/metabgcidentify.py", line 40, in runidentify
    spHMM_df_filtered_uniq_interval = pd.merge(spHMM_df_filtered, spHMM_df_filtered_uniq, how='inner')
  File "/research/m197897/anaconda/envs/metabgc/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 86, in merge
    validate=validate,
  File "/research/m197897/anaconda/envs/metabgc/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 631, in __init__
    self._maybe_coerce_merge_keys()
  File "/research/m197897/anaconda/envs/metabgc/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 1146, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on object and float64 columns. If you wish to proceed you should use pd.concat

```

Is it due to the fact that metabgc didn't find any hit in the metagenomic reads and terminate?

Curiously, when I try giving truncated input files (the full version of which ran successfully before), I get the same error.

**Comment by aemiol** [comment]
I am having the same error. 
Has anyone been able to successfully run this tool on their data?

**Comment by abiswas-odu** [comment]
Looks like it. Please check if the hmmer search produced any output. Does the file <output_dir>/hmm_identify_search/CombinedHmmSearch.txt have any values above the cutoffs? The cutoffs are defined in <sphmm_dir>/pfam__F1_Cutoff.tsv. In case of the test data it is defined in output/build/HiPer_spHMMs/Cyclase_OxyN_F1_Cutoff.tsv. If all the hmmer searches are below the cutoff then please try adjusting the cutoffs.

**Comment by aemiol** [comment]
Thanks for the quick reply.

1. <output_dir>/hmm_identify_search/CombinedHmmSearch.txt is blank. And how do you adjust the cutoff in "metabgc search" module? I thought you only adjust thresholds at "metabgc build"?

2. Also, running data with the pre-built high-performance spHMMs you provided throws up the following error; 
File MetaBGC/MetaBGC-V1/MetaBGC-Build_Outputs/Cyclase_OxyN/Cyclase_OxyN_F1_Cutoff.tsv does not exist.

I think you need a clearer and simpler example

**Comment by abiswas-odu** [comment]
1. Is the CombinedHmmSearch.txt blank for the example provided in [https://github.com/donia-lab/MetaBGC#quick-start](https://github.com/donia-lab/MetaBGC#quick-start)? If so the issue might be something different related to hmmer install. If the issue is with your real world read library it also could be a data issue considering that cyclases are rare in metagenomic datasets. 

2. Please use the example input linked in the section : https://github.com/donia-lab/MetaBGC#quick-start 
The spHMMs cutoff should be in ${OP_PATH}/build/HiPer_spHMMs. We changed the extension and the format of the cutoff file to have more information since MetaBGC-V1. That cutoff file is not compatible anymore with the current software release.

**Comment by aemiol** [comment]
How do I then get  pre-built high-performance spHMMs for non-cyclases that will be compatible with current release?

**Comment by abiswas-odu** [comment]
We plan to provide a extensive list of other models in a follow-up publication.

**Comment by jefferson041** [comment]
I have the same problems as mentioned above. My hammer search result file is blank, so as suggested, I do not have hmm identity above the F1 cutoff. But I have following observations:
i) I used 10 different sets of simulated metagenomes which mimics the distribution of real-world metagenomes, but there also, I could not able to find hits above author described F1 cutoff of 0.5. May be if I lower the cutoff (<0.2), then I will get some hits. But how come in that case, they will be "high-performance" spHMMs? And if the cyclases are rare in real metagenomes, how come you get good hits in your example file with high cutoff? What is your F1 cutoff in HMP datasets?
ii) As user1 said, I also tried with a truncated version of example file (which is by the way, unnecessarily big) and I notice no hits. Your answer suggests that you should adjust your F1 cutoff until you see any results – which I don’t think is a good way of getting results.
iii) In your paper you said this software can be used in other classes of BGCs, but I don’t see a way of getting spHMMs of non-cyclases using this software right now, because in that case you need to define spHMMs first, which seems to be adjusted depending upon the dataset.

**Comment by abiswas-odu** [comment]
If the HMMER search is completely blank, then you have no hits at all. So, manually changing the **spHMM cutoff scores** (not F1 score) is not going to help. You can use the **metabgc build** to build new models for yourself. Please read Build step documentation and 

`metabgc build --help`  

To answer your other questions in detail:

1.   There are no F1 score calculations in the identify step, so we are not sure what you mean by “I could not find any hits above F1 score of 0.5”. Maybe you mean spHMM cutoff scores we discussed in the earlier response? These have different cutoffs based on the chosen models. The F1 score is specified by the user in the build step and is used to select the best performing models. It is obviously very much dependent on the synthetic dataset and the protein family of interest, but we found the 0.5 to work well. The cutoff of 0.5 was chosen based on the cyclase spHMMs, and our human microbiome simulated datasets with spiked positives (please see publication). We also tried in the paper the same cutoff with two additional protein families from two additional classes of BGCs, using the same synthetic dataset, and it was still good at separating high and low-performing spHMMs.  We don’t suggest lowering the F1 score at the time of spHMM selection. We suggest maybe slightly lowering the spHMM score cutoff at the identify step (still using only the high performance models) in case your cyclase hits are very distant, but this can certainly result in more false positives. We have not tried this ourselves. Our spHMM cutoffs chosen from the build step were sufficient in identifying all the hits in the paper. 

2. We designed our example file so that you do get some hits and make sure the tool completes successfully as a test. **Arbitrarily truncating the search dataset is removing reads that hit the spHMMs during the hmmer search.** If you would like a real life example where you can find or not find hits, you will need to run >3000 metagenomes we used in the paper (all publicly available). T2PKS Cyclases are indeed rare in human microbiome metagenomes (and metagenomes and bacterial genomes in general).

3. You can use the **build module**, an alignment of your choice, and a synthetic dataset of your design to develop spHMMs for any protein family of interest (please see publication). There is nothing special about the cyclases. If you want good performing models to search human microbiome samples, you need to develop the spHMMs using a synthetic human microbiome dataset. If you will search a soil microbiome one, you need to develop them using a synthetic dataset that mimics a soil metagenome background, and so on. We are currently doing it ourselves and developing pre-built spHMMs for several biosynthetic classes. We will be providing these in a follow up publication.

**Comment by aemiol** [comment]
This is even more confusing and complicated than initially thought! Almost impossible to run this tool

**Comment by alexthm341** [comment]
I face the same problem and now I highly doubt about the usefulness of this software. Set aside frequent crashes, non-ending loops and blank results, I thought I could use this to detect BGCs in metagenome for further analysis, but if a user needs to create –build models for each of his domain of interest one by one and then using that model try to search a metagenome, only the BGC detection work is going to be cumbersome and it defies the justification of a ‘BGC-detection’ software.

**Comment by aemiol** [comment]
@alexthm341 Totally agree. The software is of no use at current state
