### ISSUE TITLE
Toy build for MetaBGC v1.3.3

### ISSUE THREAD

**Issue by deucy646** [donia-lab/MetaBGC#7]
I tried MetaBGC v1.3.3 with toy OxyN build from Google drive link. Some files are missing from the 'HiPer_spHMMs' folder of "OxyN" toy build. The missing files as stated by MetaBGC v1.3.3 as follows:

* <prot_family_name>_Scores.tsv: FP, TP and FN scores of the the HMM search for all the spHMMs.
* <prot_family_name>_FP_Reads.tsv: False positive reads in the HMM search but not in the BLAST search.

Can you provide the updated, suitable and complete toy build for MetaBGC v1.3.3. It would be a great help.

**Comment by Junyu25** [comment]
Yeah, I meet the same problem. I think the Google drive build file they provide is for the old version of MetaBGC.
I guess the problem is they didn't provide the `true positive genes fasta file` (only have a `TPGenes.faa`  file, but what we need is the "Multi-FASTA with the nucleotide sequence of the true positive genes"), so we can't generate the `<prot_family_name>_Scores.tsv` or `<prot_family_name>_FP_Reads.tsv` file by the process.
I think this method has a great potential, and I also want to adapt it to our project. So I hope @frcamacho @abiswas-odu you guys can provide the missing file for us to a demo.

**Comment by abiswas-odu** [comment]
The Google drive files are a small toy test for metabgc search. The method to to build a database requires creating a background of synthetic reads with the true positive genomes is described in the publication.
